name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Docker build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./financial_dashboard
          file: ./financial_dashboard/Dockerfile.backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/financial_dashboard-backend:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./financial_dashboard
          file: ./financial_dashboard/Dockerfile.frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/financial_dashboard-frontend:latest

      - name: Deploy backend to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_BACKEND_ID: ${{ secrets.RENDER_BACKEND_ID }}
        run: |
          curl -X POST \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{"image":"docker.io/${{ secrets.DOCKER_USERNAME }}/financial_dashboard-backend:latest"}' \
          https://api.render.com/v1/services/$RENDER_BACKEND_ID/deploys

      - name: Deploy frontend to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_FRONTEND_ID: ${{ secrets.RENDER_FRONTEND_ID }}
        run: |
          curl -X POST \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{"image":"docker.io/${{ secrets.DOCKER_USERNAME }}/financial_dashboard-frontend:latest"}' \
          https://api.render.com/v1/services/$RENDER_FRONTEND_ID/deploys
